; Session bus for sway, mako, portals.
[program:dbus-session]
command=dbus-daemon --session --nofork --nopidfile --address=%(ENV_DBUS_SESSION_BUS_ADDRESS)s
user=%(ENV_GHOSTDESK_USER)s
priority=10
autorestart=true
startretries=10
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
