# -*- coding: utf-8 -*-
"""CrewAI_MultiAgent_Gemini_Marktechpost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B3vKiaYuxdn7lKPGvv9LnNDq0_oGv4zj
"""

import os
import sys
import getpass
from textwrap import dedent

print("Installing CrewAI and tools... (this may take 1-2 mins)")
!pip install -q crewai crewai-tools

from crewai import Agent, Task, Crew, Process, LLM

print("\n--- API Authentication ---")
api_key = None

try:
    from google.colab import userdata
    api_key = userdata.get('GEMINI_API_KEY')
    print("✅ Found GEMINI_API_KEY in Colab Secrets.")
except Exception:
    pass

if not api_key:
    print("ℹ️  Key not found in Secrets.")
    api_key = getpass.getpass("🔑 Enter your Google Gemini API Key: ")

os.environ["GEMINI_API_KEY"] = api_key

if not api_key:
    sys.exit("❌ Error: No API Key provided. Please restart and enter a key.")

gemini_flash = LLM(
    model="gemini/gemini-2.0-flash",
    temperature=0.7
)

researcher = Agent(
    role='Tech Researcher',
    goal='Uncover cutting-edge developments in AI Agents',
    backstory=dedent("""You are a veteran tech analyst with a knack for finding emerging trends before they become mainstream. You specialize in Autonomous AI Agents and Large Language Models."""),
    verbose=True,
    allow_delegation=False,
    llm=gemini_flash
)

writer = Agent(
    role='Technical Writer',
    goal='Write a concise, engaging blog post about the researcher's findings',
    backstory=dedent("""You transform complex technical concepts into compelling narratives. You write for a developer audience who wants practical insights without fluff."""),
    verbose=True,
    allow_delegation=False,
    llm=gemini_flash
)

research_task = Task(
    description=dedent("""Conduct a simulated research analysis on 'The Future of Agentic AI in 2025'. Identify 3 key trends: 1. Multi-Agent Orchestration 2. Neuro-symbolic AI 3. On-device Agent execution Provide a brief summary for each based on your 'expert knowledge'."""),
    expected_output="A structured list of 3 key AI trends with brief descriptions.",
    agent=researcher
)

write_task = Task(
    description=dedent("""Using the researcher's findings, write a short blog post (approx 200 words). The post should have: - A catchy title - An intro - The 3 bullet points - A conclusion on why developers should care."""),
    expected_output="A markdown-formatted blog post.",
    agent=writer,
    context=[research_task]
)

tech_crew = Crew(
    agents=[researcher, writer],
    tasks=[research_task, write_task],
    process=Process.sequential,
    verbose=True
)

print("\n--- 🤖 Starting the Crew ---")
result = tech_crew.kickoff()

from IPython.display import Markdown
print("\n\n########################")
print("##   FINAL OUTPUT     ##")
print("########################\n")
display(Markdown(str(result)))